@extends('layouts.app')
@section('content')
    <section class="main-content-start">
        <div class="container">
            <h1>Test ทดสอบ</h1>
            <h1 class="title">Test Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officia, ullam?</h1>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate vero earum voluptatibus aliquam, ea ab, fugit rem, beatae quo aut illum perspiciatis consequuntur vel. Eaque consequatur quidem doloribus doloremque accusantium. Totam libero eos facere saepe voluptatibus ipsam assumenda maiores atque, odio ducimus consequatur hic at inventore? Nobis odio commodi accusamus est autem sed, officiis nulla sequi doloribus dolor, tenetur animi voluptatum nihil ratione earum fugiat vel praesentium consequuntur porro sapiente. Doloribus excepturi itaque quam dolores ea perspiciatis illo doloremque ipsa minima? Repudiandae quo laudantium dolorum, quas totam iste provident. Suscipit nemo molestiae, aspernatur adipisci doloremque perferendis quidem necessitatibus quam obcaecati? Iure nobis soluta non voluptatem magnam, eaque optio aspernatur quia. Perferendis nulla saepe labore nesciunt, ut asperiores quos molestias tempora. Praesentium natus assumenda necessitatibus eum, repellat eius quod soluta dolor quos exercitationem repudiandae odit architecto accusamus et beatae sequi expedita! Suscipit, facilis eaque praesentium maiores, non nesciunt magnam accusamus saepe quibusdam pariatur sit quia quae odio impedit fugiat voluptatem! Doloribus, quo consequatur consequuntur incidunt voluptate, a non fuga debitis quidem est iure assumenda? Pariatur impedit exercitationem nam incidunt nostrum placeat est cumque aliquam! Consectetur ex error ea, dignissimos id similique! Blanditiis, modi delectus. Aspernatur similique at temporibus minus hic quidem?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet veritatis libero quasi distinctio quaerat similique quae aliquam at impedit necessitatibus enim officiis, corporis, ipsam assumenda blanditiis iusto, molestias amet tempore. Non quam repellendus dicta cupiditate unde ut qui esse, incidunt perspiciatis, tempora tenetur sed perferendis vero velit accusantium assumenda sit!</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate vero earum voluptatibus aliquam, ea ab, fugit rem, beatae quo aut illum perspiciatis consequuntur vel. Eaque consequatur quidem doloribus doloremque accusantium. Totam libero eos facere saepe voluptatibus ipsam assumenda maiores atque, odio ducimus consequatur hic at inventore? Nobis odio commodi accusamus est autem sed, officiis nulla sequi doloribus dolor, tenetur animi voluptatum nihil ratione earum fugiat vel praesentium consequuntur porro sapiente. Doloribus excepturi itaque quam dolores ea perspiciatis illo doloremque ipsa minima? Repudiandae quo laudantium dolorum, quas totam iste provident. Suscipit nemo molestiae, aspernatur adipisci doloremque perferendis quidem necessitatibus quam obcaecati? Iure nobis soluta non voluptatem magnam, eaque optio aspernatur quia. Perferendis nulla saepe labore nesciunt, ut asperiores quos molestias tempora. Praesentium natus assumenda necessitatibus eum, repellat eius quod soluta dolor quos exercitationem repudiandae odit architecto accusamus et beatae sequi expedita! Suscipit, facilis eaque praesentium maiores, non nesciunt magnam accusamus saepe quibusdam pariatur sit quia quae odio impedit fugiat voluptatem! Doloribus, quo consequatur consequuntur incidunt voluptate, a non fuga debitis quidem est iure assumenda? Pariatur impedit exercitationem nam incidunt nostrum placeat est cumque aliquam! Consectetur ex error ea, dignissimos id similique! Blanditiis, modi delectus. Aspernatur similique at temporibus minus hic quidem?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet veritatis libero quasi distinctio quaerat similique quae aliquam at impedit necessitatibus enim officiis, corporis, ipsam assumenda blanditiis iusto, molestias amet tempore. Non quam repellendus dicta cupiditate unde ut qui esse, incidunt perspiciatis, tempora tenetur sed perferendis vero velit accusantium assumenda sit!</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate vero earum voluptatibus aliquam, ea ab, fugit rem, beatae quo aut illum perspiciatis consequuntur vel. Eaque consequatur quidem doloribus doloremque accusantium. Totam libero eos facere saepe voluptatibus ipsam assumenda maiores atque, odio ducimus consequatur hic at inventore? Nobis odio commodi accusamus est autem sed, officiis nulla sequi doloribus dolor, tenetur animi voluptatum nihil ratione earum fugiat vel praesentium consequuntur porro sapiente. Doloribus excepturi itaque quam dolores ea perspiciatis illo doloremque ipsa minima? Repudiandae quo laudantium dolorum, quas totam iste provident. Suscipit nemo molestiae, aspernatur adipisci doloremque perferendis quidem necessitatibus quam obcaecati? Iure nobis soluta non voluptatem magnam, eaque optio aspernatur quia. Perferendis nulla saepe labore nesciunt, ut asperiores quos molestias tempora. Praesentium natus assumenda necessitatibus eum, repellat eius quod soluta dolor quos exercitationem repudiandae odit architecto accusamus et beatae sequi expedita! Suscipit, facilis eaque praesentium maiores, non nesciunt magnam accusamus saepe quibusdam pariatur sit quia quae odio impedit fugiat voluptatem! Doloribus, quo consequatur consequuntur incidunt voluptate, a non fuga debitis quidem est iure assumenda? Pariatur impedit exercitationem nam incidunt nostrum placeat est cumque aliquam! Consectetur ex error ea, dignissimos id similique! Blanditiis, modi delectus. Aspernatur similique at temporibus minus hic quidem?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet veritatis libero quasi distinctio quaerat similique quae aliquam at impedit necessitatibus enim officiis, corporis, ipsam assumenda blanditiis iusto, molestias amet tempore. Non quam repellendus dicta cupiditate unde ut qui esse, incidunt perspiciatis, tempora tenetur sed perferendis vero velit accusantium assumenda sit!</p>
            <p style="color:red;">Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore libero consectetur, repellendus distinctio consequuntur eaque. Quisquam accusantium dolore cumque? Laborum omnis laudantium incidunt beatae pariatur quibusdam corrupti. Nemo, enim animi! Quo nisi autem praesentium dolores laborum blanditiis minus unde necessitatibus provident quos a id illo magnam odio, pariatur quidem possimus ratione ad veniam accusantium repellat iste mollitia. Velit adipisci, autem maxime in aliquam omnis perferendis dolorum explicabo quas repellat distinctio quos quasi placeat hic delectus harum, itaque eveniet sapiente inventore reiciendis! Commodi ex aut sint consequatur delectus qui veritatis. Minima aperiam obcaecati molestiae earum dolorum excepturi est doloribus architecto dolores.</p>
        </div>
    </section>
    <section class="banner">
    </section>
    <section class="main-content">
        <div class="container">
            <h1>Test ทดสอบ</h1>
            <h1 class="title">Test Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officia, ullam?</h1>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate vero earum voluptatibus aliquam, ea ab, fugit rem, beatae quo aut illum perspiciatis consequuntur vel. Eaque consequatur quidem doloribus doloremque accusantium. Totam libero eos facere saepe voluptatibus ipsam assumenda maiores atque, odio ducimus consequatur hic at inventore? Nobis odio commodi accusamus est autem sed, officiis nulla sequi doloribus dolor, tenetur animi voluptatum nihil ratione earum fugiat vel praesentium consequuntur porro sapiente. Doloribus excepturi itaque quam dolores ea perspiciatis illo doloremque ipsa minima? Repudiandae quo laudantium dolorum, quas totam iste provident. Suscipit nemo molestiae, aspernatur adipisci doloremque perferendis quidem necessitatibus quam obcaecati? Iure nobis soluta non voluptatem magnam, eaque optio aspernatur quia. Perferendis nulla saepe labore nesciunt, ut asperiores quos molestias tempora. Praesentium natus assumenda necessitatibus eum, repellat eius quod soluta dolor quos exercitationem repudiandae odit architecto accusamus et beatae sequi expedita! Suscipit, facilis eaque praesentium maiores, non nesciunt magnam accusamus saepe quibusdam pariatur sit quia quae odio impedit fugiat voluptatem! Doloribus, quo consequatur consequuntur incidunt voluptate, a non fuga debitis quidem est iure assumenda? Pariatur impedit exercitationem nam incidunt nostrum placeat est cumque aliquam! Consectetur ex error ea, dignissimos id similique! Blanditiis, modi delectus. Aspernatur similique at temporibus minus hic quidem?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet veritatis libero quasi distinctio quaerat similique quae aliquam at impedit necessitatibus enim officiis, corporis, ipsam assumenda blanditiis iusto, molestias amet tempore. Non quam repellendus dicta cupiditate unde ut qui esse, incidunt perspiciatis, tempora tenetur sed perferendis vero velit accusantium assumenda sit!</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate vero earum voluptatibus aliquam, ea ab, fugit rem, beatae quo aut illum perspiciatis consequuntur vel. Eaque consequatur quidem doloribus doloremque accusantium. Totam libero eos facere saepe voluptatibus ipsam assumenda maiores atque, odio ducimus consequatur hic at inventore? Nobis odio commodi accusamus est autem sed, officiis nulla sequi doloribus dolor, tenetur animi voluptatum nihil ratione earum fugiat vel praesentium consequuntur porro sapiente. Doloribus excepturi itaque quam dolores ea perspiciatis illo doloremque ipsa minima? Repudiandae quo laudantium dolorum, quas totam iste provident. Suscipit nemo molestiae, aspernatur adipisci doloremque perferendis quidem necessitatibus quam obcaecati? Iure nobis soluta non voluptatem magnam, eaque optio aspernatur quia. Perferendis nulla saepe labore nesciunt, ut asperiores quos molestias tempora. Praesentium natus assumenda necessitatibus eum, repellat eius quod soluta dolor quos exercitationem repudiandae odit architecto accusamus et beatae sequi expedita! Suscipit, facilis eaque praesentium maiores, non nesciunt magnam accusamus saepe quibusdam pariatur sit quia quae odio impedit fugiat voluptatem! Doloribus, quo consequatur consequuntur incidunt voluptate, a non fuga debitis quidem est iure assumenda? Pariatur impedit exercitationem nam incidunt nostrum placeat est cumque aliquam! Consectetur ex error ea, dignissimos id similique! Blanditiis, modi delectus. Aspernatur similique at temporibus minus hic quidem?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet veritatis libero quasi distinctio quaerat similique quae aliquam at impedit necessitatibus enim officiis, corporis, ipsam assumenda blanditiis iusto, molestias amet tempore. Non quam repellendus dicta cupiditate unde ut qui esse, incidunt perspiciatis, tempora tenetur sed perferendis vero velit accusantium assumenda sit!</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate vero earum voluptatibus aliquam, ea ab, fugit rem, beatae quo aut illum perspiciatis consequuntur vel. Eaque consequatur quidem doloribus doloremque accusantium. Totam libero eos facere saepe voluptatibus ipsam assumenda maiores atque, odio ducimus consequatur hic at inventore? Nobis odio commodi accusamus est autem sed, officiis nulla sequi doloribus dolor, tenetur animi voluptatum nihil ratione earum fugiat vel praesentium consequuntur porro sapiente. Doloribus excepturi itaque quam dolores ea perspiciatis illo doloremque ipsa minima? Repudiandae quo laudantium dolorum, quas totam iste provident. Suscipit nemo molestiae, aspernatur adipisci doloremque perferendis quidem necessitatibus quam obcaecati? Iure nobis soluta non voluptatem magnam, eaque optio aspernatur quia. Perferendis nulla saepe labore nesciunt, ut asperiores quos molestias tempora. Praesentium natus assumenda necessitatibus eum, repellat eius quod soluta dolor quos exercitationem repudiandae odit architecto accusamus et beatae sequi expedita! Suscipit, facilis eaque praesentium maiores, non nesciunt magnam accusamus saepe quibusdam pariatur sit quia quae odio impedit fugiat voluptatem! Doloribus, quo consequatur consequuntur incidunt voluptate, a non fuga debitis quidem est iure assumenda? Pariatur impedit exercitationem nam incidunt nostrum placeat est cumque aliquam! Consectetur ex error ea, dignissimos id similique! Blanditiis, modi delectus. Aspernatur similique at temporibus minus hic quidem?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet veritatis libero quasi distinctio quaerat similique quae aliquam at impedit necessitatibus enim officiis, corporis, ipsam assumenda blanditiis iusto, molestias amet tempore. Non quam repellendus dicta cupiditate unde ut qui esse, incidunt perspiciatis, tempora tenetur sed perferendis vero velit accusantium assumenda sit!</p>
            <p style="color:red;">Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore libero consectetur, repellendus distinctio consequuntur eaque. Quisquam accusantium dolore cumque? Laborum omnis laudantium incidunt beatae pariatur quibusdam corrupti. Nemo, enim animi! Quo nisi autem praesentium dolores laborum blanditiis minus unde necessitatibus provident quos a id illo magnam odio, pariatur quidem possimus ratione ad veniam accusantium repellat iste mollitia. Velit adipisci, autem maxime in aliquam omnis perferendis dolorum explicabo quas repellat distinctio quos quasi placeat hic delectus harum, itaque eveniet sapiente inventore reiciendis! Commodi ex aut sint consequatur delectus qui veritatis. Minima aperiam obcaecati molestiae earum dolorum excepturi est doloribus architecto dolores.</p>
        </div>
    </section>
@endsection